### ISSUE TITLE
Package to exe

### ISSUE THREAD

**Issue by nopeqk** [drunkdream/turbo-tunnel#34]
Hello! I want to package this project into a single executable with pyinstaller. How can I do that?

**Comment by drunkdream** [comment]
I'm prepared to do this recently, which platform do you want?

**Comment by nopeqk** [comment]
@drunkdream I want windows please! Thanks man.

**Comment by nopeqk** [comment]
Hey, any updates?

**Comment by drunkdream** [comment]
You can download it [here](https://github.com/drunkdream/turbo-tunnel/releases/tag/v0.7.2).
